services:
  '2048-1':
    image: '2048'
    build: ./
    ports: 
      - 10101:8080
#Увы использование port-range для хоста
#и
#deploy:
#  replicas: 2
#не работает
  '2048-2':
    image: '2048'
    ports: 
      - 10102:8080
